name: norinorigame
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/levels/6normal/
    - assets/data/levels/6hard/
    - assets/data/levels/8normal/
    - assets/data/levels/8hard/
    - assets/data/levels/10normal/
    - assets/data/levels/10hard/
    - assets/data/levels/15normal/
    - assets/data/levels/15hard/